//! # D-Bus interface proxy for: `org.freedesktop.impl.portal.PermissionStore`
//!
//! This code was generated by `zbus-xmlgen` `5.4.0` from D-Bus introspection data.
//! Source: `Interface '/org/freedesktop/impl/portal/PermissionStore' from service 'org.freedesktop.impl.portal.PermissionStore' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.freedesktop.impl.portal.PermissionStore",
    default_service = "org.freedesktop.impl.portal.PermissionStore",
    default_path = "/org/freedesktop/impl/portal/PermissionStore"
)]
pub trait PermissionStore {
    /// Delete method
    fn delete(&self, table: &str, id: &str) -> zbus::Result<()>;

    /// DeletePermission method
    fn delete_permission(&self, table: &str, id: &str, app: &str) -> zbus::Result<()>;

    /// GetPermission method
    fn get_permission(&self, table: &str, id: &str, app: &str) -> zbus::Result<Vec<String>>;

    /// List method
    fn list(&self, table: &str) -> zbus::Result<Vec<String>>;

    /// Lookup method
    fn lookup(
        &self,
        table: &str,
        id: &str,
    ) -> zbus::Result<(
        std::collections::HashMap<String, Vec<String>>,
        zbus::zvariant::OwnedValue,
    )>;

    /// Set method
    fn set(
        &self,
        table: &str,
        create: bool,
        id: &str,
        app_permissions: std::collections::HashMap<&str, &[&str]>,
        data: &zbus::zvariant::Value<'_>,
    ) -> zbus::Result<()>;

    /// SetPermission method
    fn set_permission(
        &self,
        table: &str,
        create: bool,
        id: &str,
        app: &str,
        permissions: &[&str],
    ) -> zbus::Result<()>;

    /// SetValue method
    fn set_value(
        &self,
        table: &str,
        create: bool,
        id: &str,
        data: &zbus::zvariant::Value<'_>,
    ) -> zbus::Result<()>;

    /// Changed signal
    #[zbus(signal)]
    fn changed(
        &self,
        table: &str,
        id: &str,
        deleted: bool,
        data: zbus::zvariant::Value<'_>,
        permissions: std::collections::HashMap<&str, Vec<&str>>,
    ) -> zbus::Result<()>;

    /// version property
    #[zbus(property, name = "version")]
    fn version(&self) -> zbus::Result<u32>;
}
